# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodly.Neighbourhood'),
        ),
    ]
